export * from './BackButton';
export * from './Background';
export * from './Button';
export * from './ButtonSnap';
export * from './ButtonSubmit';
export * from './Concent';
export * from './Header';
export * from './Logo';
export * from './Paragraph';
export * from './RadioButton';
export * from './TextAge';
export * from './Textform';
export * from './TextId';
export * from './Textinput'
export * from './Textsame';
export * from './Start';
export * from './Spinner';
export * from './LogOutButton';